Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/static_pages/show.html.erb, app/views/users/new.html.erb, config/routes.rb, db/migrate/20200724033234_create_users.rb, db/schema.rb, spec/features/home_page/user_can_see_campaign_name_spec.rb, spec/features/users/user_registration_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb
Adds tests and functionality to allow a user to register for an account from the root page.
=> User registration

app/models/campaign.rb, app/models/character.rb, app/models/user.rb, db/migrate/20200725001809_create_characters.rb, db/migrate/20200725002604_add_campaigns_to_characters.rb, db/migrate/20200725003913_add_users_to_characters.rb, db/schema.rb, spec/models/campaign_spec.rb, spec/models/character_spec.rb, spec/models/user_spec.rb
Adds testing and migrations and etc to make characters belong to both users and campaigns.
=> Adds character relationships

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/views/static_pages/show.html.erb, app/views/users/show.html.erb, spec/features/profile_page/user_profile_page_spec.rb, spec/features/users/user_can_log_in_spec.rb, spec/features/users/user_can_log_out_spec.rb
Completes feature where a user when logging in, is brought to their profile page with the campaign name displayed, and all of their characters.
=> Finishes profile page

app/controllers/monsters_controller.rb, app/views/monsters/index.html.erb, app/views/monsters/show.html.erb, config/routes.rb, spec/features/monsters/monster_index_page_spec.rb, spec/features/monsters/monster_show_page_spec.rb
Adds Monster show page, links to show page from monster index
=> adds monster show and adds show links to monster index:

app/controllers/application_controller.rb, app/controllers/static_pages_controller.rb, app/models/campaign.rb, spec/models/campaign_spec.rb
Refactors campaign to have a class method which will select the current campaign to be the oldest active campaign. Also reworks code to use this class method instead.
=> Campaign refactoring

app/models/campaign.rb, app/models/character.rb, app/models/game_session.rb, app/models/game_session_character.rb, db/migrate/20200727204855_create_game_session.rb, db/migrate/20200727205629_add_campaigns_to_game_sessions.rb, db/migrate/20200727211546_create_game_session_characters.rb, db/schema.rb, spec/models/campaign_spec.rb, spec/models/character_spec.rb, spec/models/game_session_character_spec.rb, spec/models/game_session_spec.rb
Sets up GameSession object to represent a single session.
GameSession belongs to a campaign.
Also sets up many to many relationship between GameSessions and Characters - representing that a GameSession has many participants, Characters, and Characters will be participating in multiple sessions. (hopefully)
=> Game session

.hound.yml, .rubocop.yml, app/models/character.rb, app/models/item.rb, app/models/item_character.rb, db/migrate/20200727201753_create_items.rb, db/migrate/20200727205816_create_item_characters.rb, db/schema.rb, spec/models/character_spec.rb, spec/models/item_character_spec.rb, spec/models/item_player_spec.rb, spec/models/item_spec.rb
Resolves #16 
Take two, rebased and updated schema file to get Mike's GameSession changes in.
Creates Item model and ItemCharacter join table & model, updated Character with relationship to Item through ItemCharacter, etc., etc. Can't believe I got snookered into making the many-to-many.
State of tests:
```
........................................
Finished in 0.9328 seconds (files took 5.03 seconds to load)
40 examples, 0 failures
Coverage report generated for RSpec to /Users/dframpton/code/projects/cobalt_reserve/coverage. 411 / 411 LOC (100.0%) covered.
```
=> Item table and relationships

app/views/static_pages/show.html.erb, spec/features/home_page/user_can_see_campaign_name_spec.rb
=> added branch logic to view to handle running Rails when no active campaign is seeded

app/controllers/sessions_controller.rb, db/schema.rb, spec/features/users/user_can_log_in_spec.rb, spec/models/character_spec.rb
=> added an active boolean flag to characters, closes #13

app/assets/stylesheets/application.css, app/controllers/sessions_controller.rb, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/sessions/passwordless_new.html.erb, app/views/static_pages/show.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, config/routes.rb, config/webpack/environment.js, db/migrate/20200728031633_add_active_to_characters.rb, package.json, spec/features/users/user_can_log_in_spec.rb, spec/features/users/user_can_log_out_spec.rb, yarn.lock
Also added a minor change to passwordless auth to show a friendly message if no users were in the system instead of an empty dropdown list
=> added bootstrap, added nav bar, fixed some layouts, closes #42

app/controllers/admin/game_sessions_controller.rb, app/controllers/game_sessions_controller.rb, app/views/admin/dashboard/show.html.erb, app/views/admin/game_sessions/new.html.erb, app/views/game_sessions/show.html.erb, config/routes.rb, spec/features/admin/admin_can_create_a_game_session_with_attached_characters_spec.rb
An Admin can create a GameSession and with checkboxes, mark which characters were in attendance for that GameSession. After creation we are brought to the GameSession show page.
=> Game session create

app/controllers/users_controller.rb, app/views/users/new.html.erb, spec/features/users/user_registration_spec.rb, spec/models/user_spec.rb
This PR adds password confirmation to the user registration.
=> Add password confirmation

app/controllers/adventure_logs_controller.rb, app/models/adventure_log.rb, app/models/game_session.rb, app/models/user.rb, app/views/adventure_logs/new.html.erb, app/views/game_sessions/show.html.erb, config/routes.rb, db/migrate/20200729032305_create_adventure_log.rb, db/migrate/20200729032825_add_game_sessions_to_adventure_logs.rb, db/migrate/20200729033414_add_users_to_adventure_logs.rb, db/schema.rb, spec/features/adventure_logs/user_can_create_adventure_log_for_a_game_session_spec.rb, spec/models/adventure_log_spec.rb, spec/models/game_session_spec.rb, spec/models/user_spec.rb
Users can now create an adventure log. Game session show pages now have the logs displayed.
=> Adventure log creation

app/controllers/application_controller.rb, app/controllers/characters_controller.rb, app/controllers/sessions_controller.rb, app/views/application/_character.html.erb, app/views/characters/_form.html.erb, app/views/characters/edit.html.erb, config/routes.rb, db/migrate/20200729032215_change_character_name_to_be_unique.rb, spec/factories/character_factory.rb, spec/factories/user_factory.rb, spec/features/admin/admin_can_create_a_game_session_with_attached_characters_spec.rb, spec/features/admin/admin_goes_to_admin_dashboard_when_logging_in_spec.rb, spec/features/characters/character_creation_spec.rb, spec/features/characters/character_edit_spec.rb, spec/features/characters/user_can_see_characters_spec.rb, spec/features/home_page/user_can_see_campaign_name_spec.rb, spec/features/monsters/monster_index_page_spec.rb, spec/features/profile_page/user_profile_page_spec.rb, spec/features/users/user_log_in_spec.rb, spec/features/users/user_log_out_spec.rb, spec/rails_helper.rb
=> Character edit

app/controllers/characters_controller.rb, app/models/character.rb, app/views/characters/_form.html.erb, db/migrate/20200729054326_add_dndbeyond_to_characters.rb, db/schema.rb, spec/factories/character_factory.rb, spec/features/characters/character_creation_spec.rb, spec/features/characters/character_edit_spec.rb, spec/models/character_spec.rb
=> add dndbeyond url to characters, added some character level validations

app/controllers/admin/game_sessions_controller.rb, app/views/game_sessions/show.html.erb, spec/features/admin/admin_can_create_a_game_session_with_attached_characters_spec.rb
Game Sessions are now created with today's date.
=> Adds date creation for Game Session #closes 55

spec/factories/character_factory.rb
=> altered random level setting in character factory

spec/factories/adventure_log_factory.rb, spec/factories/game_session_character.rb, spec/factories/game_session_factory.rb, spec/factories/item_character_factory.rb, spec/factories/item_factory.rb, spec/factories/monster_factory.rb, spec/models/factorybot_spec.rb
=> added factories for all existing models

app/models/user.rb, spec/models/user_spec.rb
=> Get user active character

app/models/character.rb, app/views/admin/game_sessions/new.html.erb, spec/features/admin/admin_can_create_a_game_session_with_attached_characters_spec.rb, spec/models/character_spec.rb
Adds a scope for characters to only return active characters, makes it so that game sessions can only be created with active characters.
=> Active characters closes #66

app/controllers/characters_controller.rb, app/views/application/_character.html.erb, config/routes.rb, spec/factories/character_factory.rb, spec/features/characters/character_creation_spec.rb, spec/features/characters/character_edit_spec.rb
closes #57 
had to tweak a factorybot setting for character names, the unique attribute was failing so I added a random 3-digit number for now
=> User can toggle Character active state

app/controllers/characters_controller.rb, app/views/application/_character.html.erb, app/views/characters/show.html.erb, config/routes.rb, spec/features/characters/user_can_see_characters_spec.rb, spec/features/characters/visitor_can_see_a_character_show_page_spec.rb
A visitor can see a character's show page and on the page see the attributes for said character.
=> A vistor can see a character page

app/models/character.rb, app/views/application/_character.html.erb, app/views/characters/show.html.erb, config/locales/en.yml, spec/factories/character_factory.rb, spec/features/characters/character_creation_spec.rb, spec/features/characters/character_edit_spec.rb, spec/features/characters/visitor_can_see_a_character_show_page_spec.rb, spec/models/character_spec.rb
=> better validation error messages

app/models/character.rb, spec/models/character_spec.rb
(Didn't get these pushed in time for the merge)
=> Rubocop linter fixes, nothing to see here

app/views/admin/game_sessions/new.html.erb, spec/features/admin/admin_can_create_a_game_session_with_attached_characters_spec.rb
Resolves #92 
- Game Session create form now correctly renders character names next to checkboxes
- Name labels correctly associated with checkboxes
- Added h2 header for character section and tweaked paragraph element
- Built up feature test to check for the above
=> Game session form names

app/views/game_sessions/show.html.erb, spec/factories/user_factory.rb, spec/features/game_sessions/game_session_show_has_links_to_character_show_spec.rb
Adds character links to game session show
=> adds character links to game session show

app/models/campaign.rb, app/models/world_news.rb, app/views/static_pages/show.html.erb, db/migrate/20200806040029_create_world_news.rb, db/migrate/20200806040144_add_campaigns_to_world_news.rb, db/schema.rb, spec/factories/world_news_factory.rb, spec/features/world_news/latest_world_news_visible_on_home_page_spec.rb, spec/models/campaign_spec.rb, spec/models/world_news_spec.rb
=> World news display Closes #62

spec/factories/campaign_factory.rb, spec/factories/character_factory.rb, spec/factories/monster_factory.rb, spec/factories/user_factory.rb, spec/factories/world_news_factory.rb
Closes #115 
adds a randomly generated 4 digit hexadecimal value to things we want to be unique with factorybot
=> fixes factorybot uniqueness issues

app/views/admin/dashboard/show.html.erb, app/views/admin/foundry_key/edit.html.erb, app/views/admin/world_news/edit.html.erb, app/views/admin/world_news/new.html.erb, app/views/backstory/edit.html.erb
Closes #122 
Adds `local: true` to all of the `form_with` tags after finding that the buttons they do not work in production
=> adds local:true to all form_with forms

app/views/admin/users/show.html.erb
yeah i added a confirmation window to it.
=> adds confirmation window
